***DATA CREATION***

In [2]:
import numpy as np

In [31]:
students=np.array(['a','b','c','d'])
subjects=np.array([101,102,103])
marks=np.array([[50,45,70],
                [55,80,40],
                [85,55,35],
                [60,40,80]])
print("students:",students)
print("subjects:",subjects)
print("marks:",marks)

students: ['a' 'b' 'c' 'd']
subjects: [101 102 103]
marks: [[50 45 70]
 [55 80 40]
 [85 55 35]
 [60 40 80]]


array([[50, 45, 70],
       [55, 80, 40],
       [85, 55, 35],
       [60, 40, 80]])

***DATA EXPLORATION***

In [5]:
print("dimensions:",marks.ndim)
print("size:",marks.size)
print("shape:",marks.shape)

dimensions: 2
size: 12
shape: (4, 3)


***DATA TRANSFORMATION***

In [11]:
reshape=marks.reshape((4,3))
flatten=marks.flatten()
transpose=marks.T
print("reshaped array:",reshape)
print("flattend array:",flatten)
print("Transposed array:",transpose)

reshaped array: [[50 45 70]
 [55 80 40]
 [85 55 35]
 [60 40 80]]
flattend array: [50 45 70 55 80 40 85 55 35 60 40 80]
Transposed array: [[50 55 85 60]
 [45 80 55 40]
 [70 40 35 80]]


***DATA COMBINATION***

In [15]:
newstd_marks=np.array([[50,60,70]])

newsub_marks=np.array([[80,55,30,80]])  #after adding new subject
print("new student marks:",np.vstack((marks,newstd_marks)))

new student marks: [[50 45 70]
 [55 80 40]
 [85 55 35]
 [60 40 80]
 [50 60 70]]


***DATA MODIFICATION***

In [32]:
unique_marks=np.unique(marks)
delete=np.delete(marks,4)
print("unique marks",unique_marks)
print("deleted marks:",delete)

unique marks [35 40 45 50 55 60 70 80 85]
deleted marks: [50 45 70 55 40 85 55 35 60 40 80]


array([[50, 45, 70],
       [55, 80, 40],
       [85, 55, 35],
       [60, 40, 80]])

***DATA TYPEHANDLING***

In [34]:
data_type=marks.astype(float)
dtype_subject=subjects.astype(str)
print("datatype of marks:",data_type)
print("daattype of subject:",dtype_subject)

datatype of marks: [[50. 45. 70.]
 [55. 80. 40.]
 [85. 55. 35.]
 [60. 40. 80.]]
daattype of subject: ['101' '102' '103']


***COPY AND VIEW BEHAVIOUR***

In [35]:
copy=np.copy(marks)
copy[0][1]=60
view=marks.view()
view[1][2]=90
print("original marks:",marks)
print("copy array:",copy)
print("view array:",view)


original marks: [[50 45 70]
 [55 80 90]
 [85 55 35]
 [60 40 80]]
copy array: [[50 60 70]
 [55 80 40]
 [85 55 35]
 [60 40 80]]
view array: [[50 45 70]
 [55 80 90]
 [85 55 35]
 [60 40 80]]
